# Generated by Django 4.0.4 on 2022-05-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='army_part',
            field=models.CharField(blank=True, max_length=300, verbose_name='Род войск'),
        ),
        migrations.AlterField(
            model_name='face',
            name='army',
            field=models.CharField(max_length=300, verbose_name='Армия'),
        ),
    ]
