# Generated by Django 4.0.4 on 2022-05-31 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_face_army_part_alter_face_army'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.CharField(max_length=300, verbose_name='Ссылка на фото')),
                ('date', models.CharField(blank=True, max_length=4, verbose_name='Год')),
                ('place', models.TextField(blank=True, verbose_name='Место')),
                ('source', models.TextField(blank=True, verbose_name='Источник')),
                ('real_author', models.TextField(blank=True, verbose_name='Реальный автор')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
    ]
