# Generated by Django 4.0.4 on 2022-05-31 14:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
