# Generated by Django 4.0.4 on 2022-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_quote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='type',
            field=models.CharField(choices=[('Гражданский', 'Гражданский'), ('Военный', 'Военный')], default=1, max_length=300, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
