# Generated by Django 4.0.4 on 2022-06-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='country',
            field=models.CharField(choices=[], max_length=300, verbose_name='Нация'),
        ),
    ]
