# Generated by Django 4.0.4 on 2022-06-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_face_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='Страна'),
        ),
    ]
