# Generated by Django 4.0.4 on 2022-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_face_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='country',
            field=models.CharField(max_length=300, verbose_name='Нация'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
