# Generated by Django 4.0.4 on 2022-06-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_newscomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsComment',
        ),
    ]
