# Generated by Django 4.0.4 on 2022-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_newscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='type',
            field=models.CharField(choices=[('Литература', 'Литература'), ('Документ', 'Документ'), ('Воспоминания', 'Воспоминания')], default=1, max_length=300, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
