# Generated by Django 4.0.4 on 2022-06-02 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_alter_quote_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.CharField(blank=True, max_length=4, verbose_name='Год')),
                ('place', models.TextField(blank=True, verbose_name='Место')),
                ('source', models.TextField(blank=True, verbose_name='Источник')),
                ('real_author', models.TextField(blank=True, verbose_name='Реальный автор')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Цитата дня',
                'verbose_name_plural': 'Цитаты дня',
            },
        ),
    ]
