# Generated by Django 4.0.4 on 2022-06-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_quoteoftheday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='type',
            field=models.CharField(choices=[('Литература', 'Литература'), ('Документ', 'Документ'), ('Воспоминания', 'Воспоминания')], max_length=300, verbose_name='Тип'),
        ),
    ]
